### ISSUE TITLE
auto-completion elsewhere than class

### ISSUE THREAD

**Issue by AdrienLemaire** [iamcco/coc-tailwindcss#16]
Related to #15 

I'm working with d3.js, and using tailwindcss classes with the `.classed()` d3 method

```js
d3.selectAll('circle')
    .classed('fill-current text-red-300', true);
```
I'd like to have coc-tailwindcss auto-completion when my cursor is within a `classed("")`, but so far coc-tailwindcss seems to only autocomplete html elements within a `class=""`. I couldn't understand where in your code you're setting this completion rule. Can we add custom locations to trigger coc-tailwindcss?

**Comment by iamcco** [comment]
It's not support.

Seams code here https://github.com/iamcco/coc-tailwindcss/blob/master/lsp/tailwindcss-language-server/dist/index.js#L6867

Why the LSP code here https://github.com/iamcco/coc-tailwindcss/pull/10#issuecomment-541756855

**Comment by AdrienLemaire** [comment]
Roger that, thanks for the reply

**Comment by dylanirlbeck** [comment]
@iamcco How difficult would it be to add this feature? For example, I created a [ReasonML ppx for Tailwind](https://github.com/dylanirlbeck/tailwind-ppx), and it'd be nice to get className autocompletion when you're inside the PPX. E.g.

```reason
<Component className=[%tw "flex ..."] /> // get autocomplete inside of the string
```

**Comment by iamcco** [comment]
@dylanirlbeck you can checkout https://github.com/iamcco/coc-tailwindcss/pull/20/files

**Comment by dylanirlbeck** [comment]
@iamcco So I followed the model you sent me for Elm support, but I'm still unable to get the suggestions to show up. This is the regex I'm using:

```
\bclass(Name)?[= ](?:\[%tw )?["']([^"']*)$/.
```

Do you know if there's another issue that could be happening? Thanks!

**Comment by dylanirlbeck** [comment]
So it looks like changing this line

```es6
// Line 6908
return o.substr(t).indexOf(e[2]) === -1;
```

to 

```es6
// Line 6908
return true
```

in addition to changing the regexp in the same places as the Elm support PR solved the issue. Can I get confirmation that this is the right approach? Thanks so much!

**Comment by iamcco** [comment]
I had review your PR.

**Comment by AdrienLemaire** [comment]
Closing this issue, because I've found other solutions for tailwind css completion: typescript libraries like https://github.com/muhammadsammy/tailwindcss-classnames and https://github.com/dvkndn/typed.tw
