### ISSUE TITLE
hbs does not support

### ISSUE THREAD

**Issue by far-fetched** [iamcco/coc-tailwindcss#23]
In the same project, coc-tailwindcss for *.html works fine. When I switch into *.hbs file it doesn't work. In readme there is information that is supports handlebars. Should I configure something extra if want to use with .hbs files ?

**Comment by iamcco** [comment]
I don't know check your filetype

**Comment by far-fetched** [comment]
Ok my handlebars files have filetype `html.handlebars`. I just added it into `tailwindCSS.htmlLanguages` settting and works. 
Thanks for help and hint.
