### ISSUE TITLE
It works under 1.0 ?

### ISSUE THREAD

**Issue by rodrigore** [iamcco/coc-tailwindcss#3]
Hi, Now that tailwind reach an stable version I was wondering if it works. I was trying this repo https://github.com/tailwindcss/playground and under my (neo)vim doesn't works.

I try to put the config under the json file and also as a 'g:coc_user_config' property on my vimrc.

Thanks

**Comment by iamcco** [comment]
1.0 is not support yet.

**Comment by iamcco** [comment]
I have updated the plugin to the latest version v0.2.0. Please update and have a try.

**Comment by rodrigore** [comment]
Thanks, works perfect!
