### ISSUE TITLE
Support for Elm language

### ISSUE THREAD

**Issue by pehota** [iamcco/coc-tailwindcss#5]
Hi,

I am using tailwind with Elm for one of my projects. 
Currently coc-tailwindcss doesn't support Elm and I was wondering if it could be added.
I am willing to do this myself but I can't really understand how to debug the extension.
I would be glad for any help to add the support.

Thanks

**Comment by iamcco** [comment]
document here: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server

**Comment by iamcco** [comment]
It depend on the tailwincss config in project and languageid (the open file)

https://github.com/iamcco/coc-tailwindcss/blob/master/src/index.ts#L20-L58

**Comment by pehota** [comment]
Awesome, thanks :)
I will give it a shot with the debugger docs.
