### ISSUE TITLE
Multiple filetypes (html.twig)

### ISSUE THREAD

**Issue by jorenvanhee** [iamcco/coc-tailwindcss#9]
The classname suggestions only work if the filetype is `html`. Is it possible to make this work if the filetype is `html.twig` (or anything else combined with html)?

Works after running this in vim: `:set ft=html`. Doesn't work after running this: `:set ft=html.twig`.

Anyway, great plugin!

**Comment by iamcco** [comment]
Need upstream lsp to support, it's not open source so it's hard to support that.

**Comment by jrock2004** [comment]
I am confused to why this needs to be upstream when it seems like you have the same file as the upstream. What am I missing

**Comment by jrock2004** [comment]
Oh, I see. So if you edit `~/.config/coc/extensions/node_modules/coc-tailwindcss/node_modules/tailwindcss-language-server/dist/index.js` and add the file ext it works.

**Comment by iamcco** [comment]
Now, it can use `tailwindCSS.htmlLanguages`, `tailwindCSS.cssLanguages`, `tailwindCSS.jsLanguages` to config languages for autocomplete by the client.
